{% set version = "0.7-2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-dirichletreg
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/DirichletReg_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/DirichletReg/DirichletReg_{{ version }}.tar.gz
  sha256: 088b4c8cf4c87e661c741a87791f8bbbbe55175d76d4ed0a7b24e7fe76782d9b

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-formula
    - r-maxlik
  run:
    - r-base
    - r-formula
    - r-maxlik

test:
  commands:
    - $R -e "library('DirichletReg')"           # [not win]
    - "\"%R%\" -e \"library('DirichletReg')\""  # [win]

about:
  home: https://github.com/maiermarco/DirichletReg https://CRAN.R-project.org/package=DirichletReg
  license: GPL-2.0-or-later
  summary: Implements Dirichlet regression models in R.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: DirichletReg
# Type: Package
# Version: 0.7-0
# Date: 2020-05-28
# Title: Dirichlet Regression in R
# Description: Implements Dirichlet regression models in R.
# Authors@R: person(given  = c("Marco", "Johannes"), family = "Maier", email  = "marco_maier@posteo.de", role   = c("cre", "aut"), comment = c(ORCID = "0000-0002-1715-7456"))
# Encoding: UTF-8
# Depends: R (>= 3.0.0), Formula
# Imports: stats, graphics, methods, maxLik
# Suggests: rgl, knitr, formatR, testthat
# License: GPL (>= 2)
# URL: https://github.com/maiermarco/DirichletReg https://CRAN.R-project.org/package=DirichletReg
# ByteCompile: yes
# LazyLoad: yes
# LazyData: yes
# ZipData: yes
# VignetteBuilder: knitr
# Author: Marco Johannes Maier [cre, aut] (<https://orcid.org/0000-0002-1715-7456>)
# Maintainer: Marco Johannes Maier <marco_maier@posteo.de>
# Repository: CRAN
# Repository/R-Forge/Project: dirichletreg
# Repository/R-Forge/Revision: 32
# Repository/R-Forge/DateTimeStamp: 2020-05-28 18:49:22
# Date/Publication: 2020-05-29 12:30:14 UTC
# NeedsCompilation: yes
# Packaged: 2020-05-28 19:13:07 UTC; rforge
